package streaming.bean.domain;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Streaming
//  @ File Name : BaseEntity.java
//  @ Date : 22/08/2012
//  @ Author : 
//
//




public class BaseEntity {
	public Object id;
}
