package streaming.bean.domain;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Streaming
//  @ File Name : Cliente.java
//  @ Date : 22/08/2012
//  @ Author : 
//
//




public class Cliente extends Persona {
	public Object correo;
	public Object fechaUltimaSesion;
	public Object horaUltimaSesion;
	public Object ultimaPeliculaVista;
	public Object tiempoUltimaPelicula;
}
