package streaming.bean.domain;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Streaming
//  @ File Name : NombreEntity.java
//  @ Date : 22/08/2012
//  @ Author : 
//
//




public class NombreEntity extends BaseEntity {
	public Object nombre;
}
