package streaming.bean.domain;
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Streaming
//  @ File Name : Pelicula.java
//  @ Date : 22/08/2012
//  @ Author : 
//
//


public class Pelicula extends NombreEntity {
	public Object resumen;
	public Object fechaEstreno;
	public Object estado;
}
