package streaming.bean.domain;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Streaming
//  @ File Name : PeliculaType.java
//  @ Date : 22/08/2012
//  @ Author : 
//
//




public class PeliculaType extends NombreEntity {
}
