package streaming.bean.domain;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Streaming
//  @ File Name : Persona.java
//  @ Date : 22/08/2012
//  @ Author : 
//
//


public class Persona extends BaseEntity {
	public Object nombres;
	public Object apellidos;
}
